parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  EasyPrm\Partner\:
    resource: '../../src/EasyPrm/Partner/'
    exclude:
      - '../../src/EasyPrm/Partner/Contract/'
      - '../../src/EasyPrm/Partner/Event/'
      - '../../src/EasyPrm/Partner/Exception/'
      - '../../src/EasyPrm/Partner/ValueObject/'

  EasyPrm\Partner\Contract\PartnerAccountRepositoryInterface:
    class: Infrastructure\Database\Orm\Doctrine\Repository\Partner\PartnerAccountRepository
  EasyPrm\Partner\Contract\PartnerUserRepositoryInterface:
    class: Infrastructure\Database\Orm\Doctrine\Repository\Partner\PartnerUserRepository
  EasyPrm\Partner\Contract\PartnerAccountNumberFactoryInterface:
    class: EasyPrm\Partner\Factory\PartnerAccountNumberFactory
  EasyPrm\Partner\Contract\PartnerAccountFactoryInterface:
    class: EasyPrm\Partner\Factory\PartnerAccountFactory
  EasyPrm\Partner\Contract\PartnerAccountBuilderInterface:
    class: EasyPrm\Partner\Builder\PartnerAccountBuilder

  EasyPrm\Partner\Command\PartnerAccount\CreateCommandHandler:
    tags:
      - {name: 'messenger.message_handler', bus: 'command.bus', method: 'handle', handles: 'EasyPrm\Partner\Command\PartnerAccount\CreateCommand'}
