doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                mapping_types:
                    identifier: string
                    amount: integer
                    currency: string
        types:
            identifier: Infrastructure\Database\Orm\Doctrine\Type\IdentifierType
            amount: Infrastructure\Database\Orm\Doctrine\Type\AmountType
            currency: Infrastructure\Database\Orm\Doctrine\Type\CurrencyType
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            EasyPrm\ProductCatalog:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Database/Orm/Doctrine/Config/ProductCatalog/'
                prefix: 'EasyPrm\ProductCatalog'
                alias: ProductCatalog
