imports:
    - { resource: services/ }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Application\:
        resource: '../src/Application/'
        exclude:
            - '../src/Application/DependencyInjection/'
            - '../src/Application/Entity/'
            - '../src/Application/Kernel.php'
            - '../src/Application/Tests/'
