imports:
    - { resource: services/ }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Application\:
        resource: '../src/Application/'
        exclude:
            - '../src/Application/DependencyInjection/'
            - '../src/Application/Entity/'
            - '../src/Application/Kernel.php'
            - '../src/Application/Tests/'
    Application\Api\ProductCatalog\Controller\:
        resource: '../src/Application/Api/ProductCatalog/Controller/'
        tags: [ 'controller.service_arguments' ]

    Application\Api\Listener\ValidationListener:
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 500}
